# Dependencies stage: install and compile everything, cached unless package*.json changes
FROM node:20-alpine AS deps

WORKDIR /app

# Install build tools for native packages (e.g. bcrypt)
RUN apk add --no-cache python3 make g++

COPY package*.json ./
RUN npm ci

# Build stage: cached node_modules, only rebuilds when source changes
FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# Production stage: keep only production dependencies, cached unless package*.json changes
FROM node:20-alpine

WORKDIR /app

COPY --from=deps /app/package*.json ./
COPY --from=deps /app/node_modules ./node_modules
RUN npm prune --omit=dev

COPY --from=builder /app/dist ./dist

# AWS DocumentDB TLS CA bundle (required when MONGODB_URI uses tls=true&tlsCAFile=...)
ADD https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem /app/global-bundle.pem

# Build args: set at build time with --build-arg
ARG MONGODB_URI
ARG ACCESS_TOKEN_SECRET
ARG REFRESH_TOKEN_SECRET
ARG ACCESS_TOKEN_DURATION_MINS
ARG REFRESH_TOKEN_DURATION_MINS
ARG PORT=3000
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG S3_PUBLIC_BUCKET_NAME
ARG S3_PUBLIC_BUCKET_REGION
ARG MAX_RESTAURANT_IMAGES
ARG MAX_RESTAURANT_IMAGE_SIZE_IN_MB
ARG PLATFORM_PERCENTAGE
ARG COLLECTION_PERCENTAGE
ARG DISBURSEMENT_PERCENTAGE
ARG ROUND_TO_NEAREST_FCFA
ARG MAX_TIME_TO_PAY_ORDER_IN_MINS
ARG FLUTTER_WAVE_URL
ARG FLUTTER_WAVE_CLIENT_PUBLIC
ARG FLUTTER_WAVE_CLIENT_SECRET
ARG FLUTTER_WAVE_MAX_PAYMENT_LINK_VALIDITY_IN_HR
ARG FLUTTER_WAVE_WEBHOOK_SECRET_HASH
ARG PLATFORM_MOBILE_MONEY_ACCOUNT_NUMBER
ARG PLATFORM_MOBILE_MONEY_NETWORK_TYPE
ARG ADMIN_EMAIL
ARG ADMIN_PASSWORD
ARG FIREBASE_SERVICE_ACCOUNT_JSON
ARG CLIENT_FRONTEND_URL
ARG RESTAURANT_FRONTEND_URL
ARG ADMIN_FRONTEND_URL

# Runtime env
ENV MONGODB_URI=${MONGODB_URI} \
    ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET} \
    REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET} \
    ACCESS_TOKEN_DURATION_MINS=${ACCESS_TOKEN_DURATION_MINS} \
    REFRESH_TOKEN_DURATION_MINS=${REFRESH_TOKEN_DURATION_MINS} \
    PORT=${PORT} \
    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
    GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
    S3_PUBLIC_BUCKET_NAME=${S3_PUBLIC_BUCKET_NAME} \
    S3_PUBLIC_BUCKET_REGION=${S3_PUBLIC_BUCKET_REGION} \
    MAX_RESTAURANT_IMAGES=${MAX_RESTAURANT_IMAGES} \
    MAX_RESTAURANT_IMAGE_SIZE_IN_MB=${MAX_RESTAURANT_IMAGE_SIZE_IN_MB} \
    PLATFORM_PERCENTAGE=${PLATFORM_PERCENTAGE} \
    COLLECTION_PERCENTAGE=${COLLECTION_PERCENTAGE} \
    DISBURSEMENT_PERCENTAGE=${DISBURSEMENT_PERCENTAGE} \
    ROUND_TO_NEAREST_FCFA=${ROUND_TO_NEAREST_FCFA} \
    MAX_TIME_TO_PAY_ORDER_IN_MINS=${MAX_TIME_TO_PAY_ORDER_IN_MINS} \
    FLUTTER_WAVE_URL=${FLUTTER_WAVE_URL} \
    FLUTTER_WAVE_CLIENT_PUBLIC=${FLUTTER_WAVE_CLIENT_PUBLIC} \
    FLUTTER_WAVE_CLIENT_SECRET=${FLUTTER_WAVE_CLIENT_SECRET} \
    FLUTTER_WAVE_MAX_PAYMENT_LINK_VALIDITY_IN_HR=${FLUTTER_WAVE_MAX_PAYMENT_LINK_VALIDITY_IN_HR} \
    FLUTTER_WAVE_WEBHOOK_SECRET_HASH=${FLUTTER_WAVE_WEBHOOK_SECRET_HASH} \
    PLATFORM_MOBILE_MONEY_ACCOUNT_NUMBER=${PLATFORM_MOBILE_MONEY_ACCOUNT_NUMBER} \
    PLATFORM_MOBILE_MONEY_NETWORK_TYPE=${PLATFORM_MOBILE_MONEY_NETWORK_TYPE} \
    ADMIN_EMAIL=${ADMIN_EMAIL} \
    ADMIN_PASSWORD=${ADMIN_PASSWORD} \
    FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON} \
    CLIENT_FRONTEND_URL=${CLIENT_FRONTEND_URL} \
    RESTAURANT_FRONTEND_URL=${RESTAURANT_FRONTEND_URL} \
    ADMIN_FRONTEND_URL=${ADMIN_FRONTEND_URL}

EXPOSE 3000

CMD ["node", "dist/main"]
