export enum EnumNotificationI18nType {
  ORDER_PREPARING_ORDER = 'ORDER_PREPARING_ORDER',
  ORDER_IN_DELIVERY = 'ORDER_IN_DELIVERY',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED_BY_RESTAURANT = 'ORDER_CANCELLED_BY_RESTAURANT',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  ORDER_PAID_RESTAURANT = 'ORDER_PAID_RESTAURANT',
  ORDER_PAID_CLIENT = 'ORDER_PAID_CLIENT',
  ORDER_PAYMENT_FAILED_CLIENT = 'ORDER_PAYMENT_FAILED_CLIENT',
}
