export enum EnumOrderStatus {
  CREATED = 'CREATED',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAID = 'PAID',
  CANCELLED_BY_RESTAURANT = 'CANCELLED_BY_RESTAURANT',
  DELIVERED = 'DELIVERED',
  DISBURSED = 'DISBURSED',
}
