export enum EnumStatusCode {
  RECOVERED_SUCCESSFULLY = 'RECOVERED_SUCCESSFULLY',
  LOGGED_IN_SUCCESSFULLY = 'LOGGED_IN_SUCCESSFULLY',
  UPDATED_SUCCESSFULLY = 'UPDATED_SUCCESSFULLY',
  DELETED_SUCCESSFULLY = 'DELETED_SUCCESSFULLY',
  CREATED_SUCCESSFULLY = 'CREATED_SUCCESSFULLY',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNABLE_TO_CREATE_ACCOUNT = 'UNABLE_TO_CREATE_ACCOUNT',
  EXISTS_ALREADY = 'EXISTS_ALREADY',
}
